#!/usr/bin/env zsh

FONT_FACE="JetBrainsMono Nerd Font"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins-laptop"
PLUGIN_SHARED_DIR="$HOME/.config/sketchybar/plugins"

# SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

sketchybar --bar \
    height=32 \
    color=0x2f655091 \
    margin=0 \
    sticky=on \
    padding_left=23 \
    padding_right=23 \
    notch_width=188 \
    display=main \

sketchybar --default \
    background.color=0x66494d64 \
    background.corner_radius=5 \
    background.padding_right=5 \
    background.height=26 \
    icon.font="$FONT_FACE:Medium:15.0" \
    icon.padding_left=5 \
    icon.padding_right=5 \
    label.font="$FONT_FACE:Medium:13.0" \
    label.color=0xffcad3f5 \
    label.y_offset=0 \
    label.padding_left=0 \
    label.padding_right=5

# spotify
# sketchybar --add event spotify_change $SPOTIFY_EVENT \
#     --add item spotify e \
#     --set spotify \
#     icon= \
#     icon.y_offset=1 \
#     icon.font="$FONT_FACE:Bold:20.0" \
#     label.drawing=off \
#     label.padding_left=3 \
#     script="$PLUGIN_DIR/spotify.sh" \
#     --subscribe spotify spotify_change mouse.clicked

# media
sketchybar --add item media e \
  --set media \
  icon=󰫔 \
  icon.font="$FONT_FACE:Bold:25.0" \
  icon.y_offset=1 \
  script="$HOME/.config/sketchybar/plugins/media.sh" \
  --subscribe media media_change mouse.clicked

sketchybar --add item current_space left \
    --set current_space \
    background.color=0xfff5a97f \
    icon.color=0xff24273a \
    icon.drawing=on \
    label.drawing=off \
    shadow=on \
    script="$PLUGIN_SHARED_DIR/current_space.sh" \
    --subscribe current_space space_change mouse.clicked

sketchybar --add item front_app left \
    --set front_app \
    background.color=0xffa6da95 \
    background.padding_left=0 \
    background.padding_right=0 \
    icon.y_offset=1 \
    icon.color=0xff24273a \
    icon.font="sketchybar-app-font:Regular:15.0" \
    icon.padding_right=4 \
    label.drawing=no \
    script="$HOME/.config/sketchybar/plugins/front_app.sh" \
    \
    --add item front_app.separator left \
    --set front_app.separator \
    background.color=0x00000000 \
    background.padding_left=-15 \
    \
    --add item front_app.name left \
    icon.padding_left=0 \
    icon.padding_right=0 \
    icon.y_offset=1 \
    label.drawing=no \
    --set front_app.name \
    background.color=0x00000000 \
    background.padding_right=0 \
    icon.drawing=off \
    label.font="$FONT_FACE:Bold:13.0" \
    label.drawing=yes \

sketchybar --add bracket front_app_bracket \
    front_app \
    front_app.separator \
    front_app.name \
    --subscribe front_app front_app_switched

# brew
sketchybar -m --add item packages q \
  --add event brew_upgrade \
  --set packages update_freq=300 \
  --set packages script="$HOME/.config/sketchybar/plugins/b.sh" \
  --set packages label="" \
  --set packages label.font="$FONT_FACE:Bold:20" \
  --set packages label.y_offset=1 \
  --set packages label.padding_right=5 \
  --set packages padding_right=-1 \
  --set packages label.padding_left=-5 \
  --subscribe packages brew_upgrade

sketchybar --add item clock right \
    --set clock \
    icon="󰃰" \
    icon.color=0xffed8796 \
    update_freq=10 \
    script="$PLUGIN_SHARED_DIR/clock.sh"

sketchybar --add item battery right \
    --set battery \
    update_freq=20 \
    script="$PLUGIN_DIR/battery.sh"

sketchybar -m --add item network_down q \
  --set network_down label.font="$FONT_FACE:Medium:12" \
  icon.font="SF Pro:Heavy:9" \
  icon=􀱈 \
  icon.highlight_color=0xff98ff98 \
  icon.y_offset=5 \
  icon.padding_right=5 \
  label.padding_left=5 \
  label.y_offset=5 \
  label.width=80 \
  label.align=right \
  y_offset=-5 \
  background.y_offset=5 \
  update_freq=2 \
  script="$HOME/.config/sketchybar/plugins/speed.sh" \
  \
  --add item network_up q \
  --set network_up label.font="$FONT_FACE:Medium:12" \
  icon.font="SF Pro:Heavy:9" \
  icon=􀄮 \
  icon.color=0xffffffff \
  icon.highlight_color=0xffffc0cb \
  icon.y_offset=5 \
  icon.padding_right=5 \
  label.padding_left=5 \
  label.y_offset=5 \
  label.width=80 \
  label.align=right \
  y_offset=-5 \
  background.y_offset=5 \

##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change
